"""App configuration, populated from environment variables."""

from __future__ import annotations

import os

from . import constants as game


class Config:
    SECRET_KEY = os.environ.get("FLASK_SECRET_KEY", "dev-secret-change-me")

    SQLALCHEMY_DATABASE_URI = os.environ.get(
        "DATABASE_URL",
        "postgresql+psycopg://silo:silo@localhost:5432/silo",
    )
    SQLALCHEMY_TRACK_MODIFICATIONS = False

    GRAFANA_URL = os.environ.get("GRAFANA_URL", "http://localhost:3000")
    GRAFANA_DASHBOARD_UID = os.environ.get("GRAFANA_DASHBOARD_UID", "silo-environment")

    # --- Game tuning (see app/constants.py) ---
    INITIAL_RADIATION = game.INITIAL_RADIATION
    RADIATION_DISPLAY_NOISE_MAX = game.RADIATION_DISPLAY_NOISE_MAX
    DECAY_TICK_SECONDS = game.DECAY_TICK_SECONDS
    DECAY_HALF_LIFE_SECONDS = game.DECAY_HALF_LIFE_SECONDS
    INITIAL_POPULATION = game.INITIAL_POPULATION
    INITIAL_LOYALTY = game.INITIAL_LOYALTY
    RADIATION_SAFE_THRESHOLD = game.RADIATION_SAFE_THRESHOLD
    BASE_DEPARTURE_RATE = game.BASE_DEPARTURE_RATE
    INITIAL_ENERGY = game.INITIAL_ENERGY
    LIGHTS_POWER_DRAW = game.LIGHTS_POWER_DRAW
    CRANK_POWER_PER_WORKER = game.CRANK_POWER_PER_WORKER
    CRANK_WORKERS_LOYALTY_THRESHOLD = game.CRANK_WORKERS_LOYALTY_THRESHOLD
    CRANK_WORKERS_LOYALTY_PENALTY = game.CRANK_WORKERS_LOYALTY_PENALTY
    MANUAL_CRANK_ENERGY = game.MANUAL_CRANK_ENERGY
    INITIAL_FOOD = game.INITIAL_FOOD
    INITIAL_FARM_WORKERS = game.INITIAL_FARM_WORKERS
    FOOD_PER_CAPITA_PER_SECOND = game.FOOD_PER_CAPITA_PER_SECOND
    FOOD_PER_WORKER_PER_SECOND = game.FOOD_PER_WORKER_PER_SECOND
    FARM_PLANT_GROWTH_SECONDS = game.FARM_PLANT_GROWTH_SECONDS
    FARM_HARVEST_YIELD = game.FARM_HARVEST_YIELD

    GAMESTATE_LOG_INTERVAL_SECONDS = game.GAMESTATE_LOG_INTERVAL_SECONDS

    INITIAL_BOREDOM = game.INITIAL_BOREDOM
    INITIAL_DOUBT = game.INITIAL_DOUBT
    INITIAL_INNER_CIRCLE_LOYALTY = game.INITIAL_INNER_CIRCLE_LOYALTY
    BOREDOM_PER_SECOND = game.BOREDOM_PER_SECOND
    DOUBT_GROWTH_MAX_PER_SECOND = game.DOUBT_GROWTH_MAX_PER_SECOND
    SOCIAL_MOVIE_COOLDOWN_SECONDS = game.SOCIAL_MOVIE_COOLDOWN_SECONDS
    SOCIAL_SPEECH_COOLDOWN_SECONDS = game.SOCIAL_SPEECH_COOLDOWN_SECONDS
    SOCIAL_COUNCIL_COOLDOWN_SECONDS = game.SOCIAL_COUNCIL_COOLDOWN_SECONDS
    SOCIAL_MOVIE_BOREDOM_RELIEF_BASE = game.SOCIAL_MOVIE_BOREDOM_RELIEF_BASE
    SOCIAL_MOVIE_DIMINISH_K = game.SOCIAL_MOVIE_DIMINISH_K
    SOCIAL_SPEECH_LOYALTY_GAIN_BASE = game.SOCIAL_SPEECH_LOYALTY_GAIN_BASE
    SOCIAL_SPEECH_DOUBT_RELIEF_BASE = game.SOCIAL_SPEECH_DOUBT_RELIEF_BASE
    SOCIAL_SPEECH_DIMINISH_K = game.SOCIAL_SPEECH_DIMINISH_K

    USER_COOKIE_NAME = "silo_user_id"
    USER_COOKIE_MAX_AGE = 60 * 60 * 24 * 365  # 1 year
